version: "2"
services:
  #app:
  #  build: ./app
  #  links:
  #  - db
  #  ports:
  #  - "5000:5000"

  gateway:
    build: ./gateway
    ports:
    - "3200:3200"

  db:
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - ./db:/docker-entrypoint-initdb.d/:ro

  flyway:
    image: arojunior/flyway:5.2.4
    command: "wait-for-it --timeout=60 --strict db:3306 -- flyway migrate"
    volumes:
      - ./flyway/config:/flyway/conf
      - ./flyway/sql:/flyway/sql
    depends_on:
      - db
